---

syntax:
  before_script:
    - bundle install
  script:
    - bundle exec rake syntax

lint:
  before_script:
    - bundle install
  script:
    - bundle exec rake lint

onceover:
  before_script:
    - bundle install
  script:
    - bundle exec onceover run spec

