---
# TODO: have onceover results published as test results in junit format, if possible

resources:
  containers:
  - container: ruby
    image: ruby:2.5

jobs:
- job: Syntax
  pool:
    vmImage: 'ubuntu-16.04'
  container: ruby
  steps:
  - script: bundle install
  - script: bundle exec rake syntax

- job: Lint
  pool:
    vmImage: 'ubuntu-16.04'
  container: ruby
  steps:
  - script: bundle install
  - script: bundle exec rake lint

- job: Onceover
  pool:
    vmImage: 'ubuntu-16.04'
  container: ruby
  steps:
  - script: bundle install
  - script: bundle exec onceover run spec

- job: Deploy Dev
  pool: 
    name: Default
  dependsOn: Syntax,Lint,Onceover
  steps:
  - script: puppet code deploy --all --wait
    